### ISSUE TITLE
issue using vision module

### ISSUE THREAD

**Issue by t0mZ4** [RMNCLDYO/grok-ai-toolkit#1]
Hi, trying to send an image, using the basic command:

python3.8 cli.py --vision --prompt "What's in this image?" --image_path image.png 

image is in the current folder

getting the following error:

```

`python3.8 cli.py --vision --prompt "What's in this image?" --image_path image.png 

Enter '/upload' at any time followed by the image path or URL and an optional prompt.
Example: /upload /path/to/image.jpg What's in this image?

Enter '/clear' to clear conversation history.
Enter '/exit' or '/quit' to end the conversation.

\ Assistant is thinking...... (0:00:01)[ ERROR ]: Unknown error: 422 Client Error: Unprocessable Entity for url: https://api.x.ai/v1/chat/completions
                                                                                                                                                    
[ SUCCESS ]: Cache folder cleaned.

Thank you for using the Grok AI toolkit. Have a great day!
`
```

**Comment by ramonclaudio** [comment]
Thanks for reporting this issue @t0mZ4! This has been fixed in our latest release [v1.1.0](https://github.com/RMNCLDYO/grok-ai-toolkit/releases/tag/v1.1.0).

If you're still experiencing this issue, please follow one of the methods listed below:

*Option 1 - Update existing clone*:
```bash
cd grok-ai-toolkit
git fetch
git pull origin main
```

*Option 2 - New clone*:
```bash
rm -rf grok-ai-toolkit
git clone https://github.com/RMNCLDYO/grok-ai-toolkit.git
cd grok-ai-toolkit
```

Also make sure:
1. Your image file exists and is under the 10MB size limit
2. You're using the correct model (grok-2-vision-1212 or grok-vision-beta)

The error you encountered was due to incorrect image payload formatting in the API request. We've updated the image handling logic to properly encode and validate images before sending them to the API.

Let me know if you need any further assistance!
